baseurl      = "http://text.baldanders.info/"
title        = "text.Baldanders.info"
languageCode = "ja"

[params]
description = "帰ってきた「しっぽのさきっちょ」"
favicon     = "/favicon.ico"
disqus      = "textbaldandersinfo"

[params.author]
name      = "Spiegel"
url       = "http://www.baldanders.info/spiegel/profile/"
avatar    = "/images/avatar.jpg"
license   = "by-sa"
github    = "spiegel-im-spiegel"
twitter   = "spiegel_2007"
medium    = "@spiegel"
instagram = "spiegel_2007"
facebook  = "spiegel.im.spiegel"
linkedin  = "spiegelimspiegel"
flattr    = "spiegel"
