theme = "baldanders-info"
baseurl = "https://text.baldanders.info/"
title = "text.Baldanders.info"
languageCode = "ja"
DefaultContentLanguage = "ja"
preserveTaxonomyNames = false
disqusShortname = "textbaldandersinfo"
dataDir = "data"
enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", "update", "date", "publishDate"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "tango"
    tabWidth = 4

[taxonomies]
  tags = "tags"
