theme           = "baldanders-info"
baseurl         = "https://text.baldanders.info/"
title           = "text.Baldanders.info"
languageCode    = "ja"
DefaultContentLanguage = "ja"
preserveTaxonomyNames = false
disqusShortname = "textbaldandersinfo"
pygmentsCodeFences = true
pygmentsUseClasses = true

[blackfriday]
  smartypants = false

[taxonomies]
  tags = "tags"

[author]
  name      = "Spiegel"
  url       = "https://baldanders.info/spiegel/profile/"
  avatar    = "/images/avatar.jpg"
  license   = "by-sa"
  github    = "spiegel-im-spiegel"
  twitter   = "spiegel_2007"
  instagram = "spiegel_2007"
  flickr    = "spiegel"
  facebook  = "spiegel.im.spiegel"

[params]
  since       = "2015-10-01"
  description = "帰ってきた「しっぽのさきっちょ」"
  favicon     = "/favicon.ico"
  favicon16png = "/favicon-16x16.png"
  favicon32png = "/favicon-32x32.png"
  favicon96png = "/favicon-96x96.png"
  locale = "ja-JP"
