theme           = "baldanders-info"
baseurl         = "https://text.baldanders.info/"
title           = "text.Baldanders.info"
languageCode    = "ja"
DefaultContentLanguage = "ja"
preserveTaxonomyNames = false
disqusShortname = "textbaldandersinfo"
pygmentsCodeFences = true
pygmentsUseClasses = true
dataDir = "data"
enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", "update", "date", "publishDate"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tags = "tags"
