theme           = "text"
baseurl         = "http://text.baldanders.info/"
title           = "text.Baldanders.info"
languageCode    = "ja"
DefaultContentLanguage = "ja"
disqusShortname = "textbaldandersinfo"

[author]
  name      = "Spiegel"
  url       = "http://www.baldanders.info/spiegel/profile/"
  avatar    = "/images/avatar.jpg"
  license   = "by-sa"
  github    = "spiegel-im-spiegel"
  twitter   = "spiegel_2007"
  tumblr    = "spiegel-im-spiegel"
  instagram = "spiegel_2007"
  flickr    = "spiegel"
  facebook  = "spiegel.im.spiegel"
  linkedin  = "spiegelimspiegel"
  flattr    = "spiegel"

[params]
  since       = "2015-10-01"
  description = "帰ってきた「しっぽのさきっちょ」"
  favicon     = "/favicon.ico"
  locale = "ja-JP"
