#!/usr/bin/env bash
set -euo pipefail

# Find div-box blocks that are likely AI-generated summaries and should be migrated to div-ai.
# Usage:
#   ./div-ai-check.sh
#   ./div-ai-check.sh content/remark

ROOT_PATH="${1:-content}"

if [[ ! -e "$ROOT_PATH" ]]; then
  echo "Error: path not found: $ROOT_PATH" >&2
  exit 1
fi

# Signals that strongly suggest AI-authored or AI-summarized content.
AI_PATTERN='kagi assistant|chatgpt|copilot|claude|gemini|generated by ai|ai[[:space:]]*に|ai[[:space:]]*による|要約|生成[[:space:]]*ai|人工知能'

while IFS= read -r -d '' file; do
  awk -v file="$file" -v aip="$AI_PATTERN" '
    BEGIN {
      in_block = 0
      block_start = 0
      block_text = ""
      pre = ""
      pre1 = ""; pre2 = ""; pre3 = ""; pre4 = ""; pre5 = ""
    }

    {
      line = $0

      if (!in_block) {
        # Keep a short sliding window of pre-context lines.
        pre5 = pre4
        pre4 = pre3
        pre3 = pre2
        pre2 = pre1
        pre1 = line
      }

      if (!in_block && line ~ /\{\{<[[:space:]]*div-box([^>]*)>\}\}/) {
        in_block = 1
        block_start = NR
        block_text = line "\n"
        pre = pre5 "\n" pre4 "\n" pre3 "\n" pre2 "\n" pre1
        next
      }

      if (in_block) {
        block_text = block_text line "\n"
        if (line ~ /\{\{<[[:space:]]*\/div-box[[:space:]]*>\}\}/) {
          # Candidate when either the block body or nearby pre-context contains AI hints.
          if (tolower(block_text) ~ aip || tolower(pre) ~ aip) {
            printf "%s:%d\n", file, block_start
          }
          in_block = 0
          block_start = 0
          block_text = ""
        }
      }
    }
  ' "$file"
done < <(find "$ROOT_PATH" -type f -name '*.md' -print0)
