@startuml
/'
 ' Factory Method Pattern
 '/
 skinparam minClassWidth 130

class Creator {
  # factoryMethod() : Product
  + anOperation()
}
class ConcreteCreator {
  + Creator {embedded}
  # factoryMethod() : Product
}

Creator <|-o ConcreteCreator : < <<delegation>>

@enduml
