@startuml
/'
 ' Factory Method Pattern
 '/
 skinparam minClassWidth 130

 abstract class Creator {
   {field} # injector : func() Product
   {method} + anOperation()
 }
 abstract class Product {
 }
 class ConcreteProduct {
 }
 class "injector() : Product" as Injector <<injector>> {
 }

hide <<injector>> member

Creator .right.> Product : <<use>> >
Product "1" <|.down. "n" ConcreteProduct
Injector "1" .right.> "1" ConcreteProduct : <<create>> >
Creator "1" .down.> "n" Injector : < <<inject>>

@enduml
