@startuml

show circle
skinparam classAttributeIconSize 10

class ClassName {
  {field} + publicField : String = "string" {read only}
  {field} - privateField : int
  {field} # protectedField : double
  {field} ~ protectedFieldInPackage : Object

  {method} + publicMethod(s : String, v : int) : void
  {method} - privateMethod() : int
  {method} # protectedMethod() : double
  {method} ~ protectedMethodInPackage() : Object
}

@enduml
