name: Auto Assign to Project

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues to project 1
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/spiegel-im-spiegel/github-pages-env/projects/1'
        column_name: 'Materials'

    - name: Assign issues with `bug` or 'now' labels to project 1
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'bug') ||
        contains(github.event.issue.labels.*.name, 'now')
      with:
        project: 'https://github.com/spiegel-im-spiegel/github-pages-env/projects/1'
        column_name: 'Issues'
